### ISSUE TITLE
While upgrading hc_base module

### ISSUE THREAD

**Issue by BipinRathod** [luigisison/odoo-fhir#100]
ParseError: "duplicate key value violates unique constraint "hc_human_name_term_name_unique"
DETAIL:  Key (name)=(Eve) already exists.
" while parsing /home/serpentcs/OpenERP/workspace/Projects/odoo-fhir/addons/hc_patient/examples/example_stock_persons.xml:27, near
<record id="hc_base.human_name_term_180" model="hc.human.name.term">
            <field name="name">Eve</field>
        </record>

**Comment by luigisison** [comment]
Delete `EVE `record from` hc_human_name_term` using PGAdmin. Then recompile `hc_patient`.
