### ISSUE TITLE
Installing version 10

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#12]
Installed Ubuntu 16.04 in VirtualBox.
Installed Odoo 10 using script from `https://github.com/Yenthe666/InstallScript/blob/10.0/odoo_install.sh`
`cd /odoo/odoo-server`
Checked if Odoo server is running with `sudo ps aux | grep odoo`
Server not running.
Typed `sudo service odoo-server start`
Server not running.

**Comment by nandan-drc** [comment]
@luigisison When the script complete the installation it will display the command to start/stop service like this:
 "Start Odoo service: sudo service <command> start"
 "Stop Odoo service: sudo service <command> stop"
Can you confirm that if it is showing that or not and if it is then try to use that command and let me know the result.

**Comment by luigisison** [comment]
Yes, the messages are showing at the completion of the installation.
