### ISSUE TITLE
4 Constraint:  low SHALL have a lower value than high

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#17]
rng-2: If present, low SHALL have a lower value than high (expression : low.empty() or high.empty() or (low <= high))

```
_sql_constraints = [	
	('high_greater_low',
	'CHECK(high >= low)',
	'Error ! High limit cannot be lower than Low limit.')
	]
```

**Comment by nandan-drc** [comment]
I think your expression is right or you can also use (high > low).
