### ISSUE TITLE
5 Patient Animal Species NOT NULL constraint

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#21]
In: `hc_patient.py`

Current:
```
class Patient(models.Model):
# ...
type = fields.Selection(
        string="Type", 
        selection=[
            ("human", "Human"), 
            ("animal", "Animal")],
        default="human",  
        help="Patient is human or animal.")
# ...
animal_species_id = fields.Many2one(
        comodel_name="hc.vs.animal.species", 
        string="Animal Species", 
        help="Identifies the high level taxonomic categorization of the kind of animal (e.g., dog, cow).")
``` 
Expected behavior:

If type = animal, animal_species_id is NOT NULL  
Error message: `Animal Species must be defined.`

**Comment by nandan-drc** [comment]
Model: hc_patient
File: hc_res_patient_views.xml

<record id="hc_res_patient_view_form" model="ir.ui.view">                                       
            <field name="name">Patient Form</field>                                
            <field name="model">hc.res.patient</field>                                  
            <field name="arch" type="xml">                                  
                <form string="Patient">
# . . . 
Replace: 
<field name="animal_species_id" attrs="{'invisible': [('type','!=','animal')]}"/>

By:
<field name="animal_species_id" attrs="{'invisible': [('type','!=','animal')],
                                                                        'required': [('type','=','animal')]}"/>
 And upgrade the module.

**Comment by luigisison** [comment]
It works.
