### ISSUE TITLE
6 Programming Error: many2many field

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#22]
Current state:

In module `hc_condition.py`,
```
class Condition(models.Model):    
    _name = "hc.res.condition"    
...                    
    category_ids = fields.Many2many(
        comodel_name="hc.vs.condition.category", 
        relation="condition_category_rel", 
        string="Categories", 
        help="A category assigned to the condition.")
```

Steps to reproduce:
* Create a condition
* `Save` and get error
```
ProgrammingError: column condition_category_rel.hc_vs_condition_category_id does not exist
LINE 1: SELECT condition_category_rel.hc_vs_condition_category_id, c...
``

**Comment by nandan-drc** [comment]
It works for me...
![issue_6](https://cloud.githubusercontent.com/assets/24417139/23165486/54648948-f862-11e6-852f-2ebabbb11122.png)
![issue_6 2](https://cloud.githubusercontent.com/assets/24417139/23165492/57dc9e26-f862-11e6-95bd-96491105a505.png)

Let me know if there is anything for the same.

**Comment by luigisison** [comment]
App works. Don't know how the programming error was resolved.
