### ISSUE TITLE
3 Display time UOM records in Allergy Intolerance Form

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#25]
In module `res.allergy.intolerance`, define

```
class AllergyIntolerance(models.Model): 
    _name = "hc.res.allergy.intolerance"

...

    onset_age_uom_id = fields.Many2one(
        comodel_name="product.uom", 
        string="Onset Age UOM",
        default="a", 
        help="Onset age unit of measure.")
```

Desired behavior:

In `Allergy Intolerance Form`, for `onset_age_uom_id`, display the records of `product.uom` where `category_id` = `uom_categ_utime`

**Comment by nandan-drc** [comment]
I am not getting any idea about **uom_categ_utime**.
It would be great if you can give me some more details about same.

**Comment by luigisison** [comment]
`product.uom` contains 7 records where the **Unit of Measure Category** is **Time**.

For example, **day**, **month**, **year**

Desired behavior:

In **Onset Age UOM**, display these 7 records

**Comment by nandan-drc** [comment]
domain = [('category_id', '=, uom_categ_utime)]

**Comment by luigisison** [comment]
```                          
<group>                 
...
<field name="onset_age_uom_id" class="oe_edit_only" attrs="{'invisible': [('onset_type','!=','age')]}" domain = [('category_id', '=', uom_categ_utime)]/>
...
</group>
```

error
```
XMLSyntaxError: AttValue: " or ' expected, line 73, column 63
```

**Comment by luigisison** [comment]
Solution: add `domain="[('category_id', '=', 'Time (UCUM)')]",` 

```
    onset_age_uom_id = fields.Many2one(
        comodel_name="product.uom", 
        string="Onset Age UOM",
        domain="[('category_id', '=', 'Time (UCUM)')]",
        default="a", 
        help="Onset age unit of measure.")
```
