### ISSUE TITLE
4 Display children in dropdown

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#26]
In `hc_res_patient`, defined **Animal Breed** as

```
class AnimalBreed(models.Model):    
    _name = "hc.vs.animal.breed"    
    _description = "Animal Breed"   
    _inherit = ["hc.value.set.contains"]

    name = fields.Char(
        string="Name", 
        help="Name of this animal breed.")
    code = fields.Char(
        string="Code", 
        help="Code of this animal breed.")
    contains_id = fields.Many2one(
        comodel_name="hc.vs.animal.breed", 
        string="Parent",
        help="Parent breed.")
    hierarchy_id = fields.Many2one(
        comodel_name="hc.vs.animal.species", 
        string="Hierarchy",
        help="Hierarchy grouping of this animal breed.")
```

Desired behavior:

In `hc_res_patient_views.xml`, **Patient Form**,

In the **Animal Breed** field, display the `name` of records that belong to the same **species** (same `hierarchy_id`). For example, when **Animal Species** is **dog**, display as a dropdown all the breeds of dogs in **Animal Breed**.  

![species breed](https://cloud.githubusercontent.com/assets/8397319/23278065/12ac0ed6-f9c5-11e6-9dda-24f453571cd9.JPG)

**Comment by nandan-drc** [comment]
domain = "[('hierarchy_id', '=', animal_species_id)]"

**Comment by luigisison** [comment]
It works!
