### ISSUE TITLE
1 Constraints: Timing Datatype

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#31]
Reference: [http://build.fhir.org/datatypes.html#timing](http://build.fhir.org/datatypes.html#timing)

Schema: [https://github.com/luigisison/odoo-fhir/blob/master/addons/hc_base/models/hc_timing.py](https://github.com/luigisison/odoo-fhir/blob/master/addons/hc_base/models/hc_timing.py)

**Comment by luigisison** [comment]
Constraints
tim-1: On Timing.repeat: if there's a duration, there needs to be duration units (expression  on Timing.repeat: duration.empty() or durationUnit.exists())

tim-2: On Timing.repeat: if there's a period, there needs to be period units (expression  on Timing.repeat: period.empty() or periodUnit.exists())
tim-4: On Timing.repeat: duration SHALL be a non-negative value (expression  on Timing.repeat: duration.exists() implies duration >= 0)
tim-5: On Timing.repeat: period SHALL be a non-negative value (expression  on Timing.repeat: period.exists() implies period >= 0)
tim-6: On Timing.repeat: If there's a periodMax, there must be a period (expression  on Timing.repeat: periodMax.empty() or period.exists())
tim-7: On Timing.repeat: If there's a durationMax, there must be a duration (expression  on Timing.repeat: durationMax.empty() or duration.exists())
tim-8: On Timing.repeat: If there's a countMax, there must be a count (expression  on Timing.repeat: countMax.empty() or count.exists())
tim-9: On Timing.repeat: If there's an offset, there must be a when (and not C, CM, CD, CV) (expression  on Timing.repeat: offset.empty() or (when.exists() and ((when in ('C' | 'CM' | 'CD' | 'CV')).not())))
tim-10: On Timing.repeat: If there's a timeOfDay, there cannot be be a when, or vice versa (expression  on Timing.repeat: timeOfDay.empty() or when.empty())

**Comment by luigisison** [comment]
Repo has been updated with the Timing Form. 

Also implemented the constraints.

Could not get the menuitems for Timing to display. Enter http://localhost:8069/web#id=1&view_type=form&model=hc.timing&action=630 to display the views.

**Comment by luigisison** [comment]
2017-05-05 07:06:32,553 2549 WARNING FHIR-DEV openerp.models.schema: Table 'hc_timing_repeat': unable to add 'CHECK(bounds_range_high >= bounds_range_low)' constraint !
 If you want to have it, you should update the records and execute manually:
ALTER TABLE "hc_timing_repeat" ADD CONSTRAINT "hc_timing_repeat_range_high_gt_low" CHECK(bounds_range_high >= bounds_range_low)

2017-05-05 07:06:32,589 2549 INFO FHIR-DEV openerp.sql_db: bad query: ALTER TABLE "hc_timing_repeat" ADD CONSTRAINT "hc_timing_repeat_frequency_max_gt_frequency" CHECK(frequency_max >= frequency)

2017-05-05 07:06:32,590 2549 WARNING FHIR-DEV openerp.models.schema: Table 'hc_timing_repeat': unable to add 'CHECK(frequency_max >= frequency)' constraint !
 If you want to have it, you should update the records and execute manually:
ALTER TABLE "hc_timing_repeat" ADD CONSTRAINT "hc_timing_repeat_frequency_max_gt_frequency" CHECK(frequency_max >= frequency)

**Comment by luigisison** [comment]
I drafted individual SQL constraints. Then combined SQL constraints to a single statement (per Bipin)

```
class TimingRepeat(models.Model):   
    _name = "hc.timing.repeat"  
    _description = "Timing Repeat"
...
    _sql_constraints = [    
        ('bounds_duration_gt_zero',
        'CHECK(bounds_duration >= 0.0)',
        'Bounds Duration SHALL be a non-negative value.'),

        ('range_low_gt_zero',              
        'CHECK(bounds_range_low >= 0.0)',                
        'Range Low SHALL be a non-negative value.'),

        ('range_high_gt_low',
        'CHECK(bounds_range_high >= bounds_range_low)',
        'Range High SHALL not be lower than Range Low.'),

        ('period_end_gt_start',
        'CHECK(bounds_period_end_date >= bounds_period_start_date)',
        'Period End Date SHALL not be lower than Period Start Date.'),

        ('count_max_gt_count',
        'CHECK(count_max >= count)',
        'Maximum Count SHALL not be lower than Count.'),

        ('duration_gt_zero',
        'CHECK(duration >= 0.0)',
        'Duration SHALL be a non-negative value.'),

        ('duration_max_gt_duration',
        'CHECK(duration_max >= duration)',
        'Maximum Duration SHALL not be lower than Duration.'),

        ('frequency_gt_zero',
        'CHECK(frequency >= 0.0)',
        'Frequency SHALL be a non-negative value.'),

        ('frequency_max_gt_frequency',
        'CHECK(frequency_max >= frequency)',
        'Maximum Frequency SHALL not be lower than Frequency.'),

        ('period_gt_zero',
        'CHECK(period >= 0.0)',
        'Period SHALL be a non-negative value.'),

        ('period_max_gt_period',
        'CHECK(period_max >= period)',
        'Maximum Period SHALL not be lower than Period.')  
        ]

```

**Comment by lasley** [comment]
Except for basic unique constraints, it's best to do your checks in methods instead. This allows for developer control in inherited modules, and will still work if a field is redeclared as computed.
```
from odoo import _, exceptions
...
@api.multi
@api.constrains('bounds_duration')
def _check_bounds_duration(self):
    for record in self:
        if record < 0:
            raise exceptions.ValidationError(_('No negatives'))
```
