### ISSUE TITLE
2 Compute Allergy Intolerance Name

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#32]
Data Model: ```hc.res.allergy.intolerance``` found [here](https://github.com/luigisison/odoo-fhir/blob/master/addons/hc_allergy_intolerance/models/hc_res_allergy_intolerance.py)

Current Code
```
name = fields.Char(
        string="Event Name",
        required="True", 
        help="Text representation of the allergy intolerance event. Patient + DOB + Allergy + Asserted Date.")
```

Required:        Compute the value of `name` by `compute="compute_name",`

**Part 1: subject**

`usual_name = hc_res_allergy_intolerance.patient_id.name`

> For example, if patient_id.name = John Patient, then
>
> usual_name = John Patient

`dob = year of patient_id.birth_date + "-" + month of patient_id.birth_date + "-" + day of patient_id.birth_date`

> For example, if patient_id.birth_date = 12/01/1995 (month, day, year), then
>
> year of patient_id.birth_date = 1995
> month of patient_id.birth_date = 01
> day of patient_id.birth_date = 12
> dob = 1995-01-12

`subject = John Patient (1995-01-12)`

**Part 2: type**

`res_type = hc_res_allergy_intolerance.code_id.name`

> For example, if code_id.name = Gluten, then
>
> type = Gluten

**Part 3: date**

`date = year of hc_res_allergy_intolerance.asserted_date + "-" + month of hc_res_allergy_intolerance.asserted_date + "-" + day of hc_res_allergy_intolerance.asserted_date`

> For example, if hc_res_allergy_intolerance.asserted_date = 5/1/2017 (month, day, year), then
> 
> year of hc_res_allergy_intolerance.asserted_date = 2017
> month of hc_res_allergy_intolerance.asserted_date = 05
> day of hc_res_allergy_intolerance.asserted_date = 01

`date = 2017-05-01`

**Part 4: Combine**

`name = John Patient (1995-01-12) Gluten 2017-05-01`

**Comment by BipinRathod** [comment]
**Step -1:** 
First we need to add 'compute' in field definition:
name = fields.Char(
        string="Event Name",
        compute="compute_name",
        required="True",
        help="Text representation of the allergy intolerance event. Patient + DOB + Allergy + Asserted Date.")

**Step-2:**
and after that, need to write a code for 'compute_name' method, because we are computing a name depends on other fields.

    @api.one
    @api.depends('patient_id', 'code_id', 'asserted_date')
    def compute_name(self):
        comp_name = '/'
        for hc_res_allergy_intolerance in self:
            if hc_res_allergy_intolerance.patient_id:
                comp_name = hc_res_allergy_intolerance.patient_id.name
                if hc_res_allergy_intolerance.patient_id.birth_date:
                    patient_b_date = datetime.strftime(datetime.strptime(hc_res_allergy_intolerance.patient_id.birth_date, DF), "%Y-%m-%d")
                    comp_name = comp_name + "("+ patient_b_date + ")"
            if hc_res_allergy_intolerance.code_id:
                comp_name = comp_name + " " + hc_res_allergy_intolerance.code_id.name or ''
            if hc_res_allergy_intolerance.asserted_date:
                patient_asserted_date = datetime.strftime(datetime.strptime(hc_res_allergy_intolerance.asserted_date, DTF), "%Y-%m-%d")
                comp_name = comp_name + " " + patient_asserted_date
            hc_res_allergy_intolerance.name = comp_name

**Note** : We are dealing with date and datetime data type, so we need to import datetime library.
from datetime import datetime
from openerp.tools import DEFAULT_SERVER_DATE_FORMAT as DF
from openerp.tools import DEFAULT_SERVER_DATETIME_FORMAT as DTF

**Comment by BipinRathod** [comment]
**Step 1:** Add import statements
    from datetime import datetime
    from openerp.tools import DEFAULT_SERVER_DATE_FORMAT as DF
    from openerp.tools import DEFAULT_SERVER_DATETIME_FORMAT as DTF

**Step 2:**  Onchange method for concatenate name fields depends on other fields

@api.onchange('patient_id', 'code_id', 'asserted_date')
def compute_name(self):
    comp_name = '/'
    for hc_res_allergy_intolerance in self:
        if hc_res_allergy_intolerance.patient_id:
            comp_name = hc_res_allergy_intolerance.patient_id.name
            if hc_res_allergy_intolerance.patient_id.birth_date:
                patient_b_date = datetime.strftime(datetime.strptime(hc_res_allergy_intolerance.patient_id.birth_date, DF), "%Y-%m-%d")
                comp_name = comp_name + "("+ patient_b_date + ")"
        if hc_res_allergy_intolerance.code_id:
            comp_name = comp_name + " " + hc_res_allergy_intolerance.code_id.name or ''
        if hc_res_allergy_intolerance.asserted_date:
            patient_asserted_date = datetime.strftime(datetime.strptime(hc_res_allergy_intolerance.asserted_date, DTF), "%Y-%m-%d")
            comp_name = comp_name + " " + patient_asserted_date
        hc_res_allergy_intolerance.name = comp_name

**Note :**  No need to change the field definition as we did previous comment
