### ISSUE TITLE
Fix singleton error in Full Human Name

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#34]
Singleton error in `hc.human.name`

**Comment by BipinRathod** [comment]
Fixed Singleton error


    @api.depends('display_order', 'prefix_ids', 'first_id', 'middle_ids', 'initial_ids', 'nickname_ids', 'mother_maiden_id', 'surname_id', 'suffix_ids', 'previous_surname_ids', 'birth_surname_id')
    def _compute_full_name(self):
        for rec in self:
            first = rec.first_id.name if rec.first_id else ''
            middle = " ".join([middle.name for middle in rec.middle_ids]) if rec.middle_ids else ''
            initial = " ".join([initial.name for initial in rec.initial_ids]) if rec.initial_ids else ''
            nickname = " ".join([nickname.name for nickname in rec.nickname_ids]) if rec.nickname_ids else ''

            if nickname == '':
                given = first + ' ' + middle + ' ' + initial
                rec.given = given
    
            if nickname != '':
                given = first + ' ' + middle + ' ' + initial + ' (' + nickname + ')'
                rec.given = given
    
            mother_maiden = rec.mother_maiden_id.name if rec.mother_maiden_id else ''
            birth_surname = rec.birth_surname_id.name if rec.birth_surname_id else ''
            previous_surname = " ".join([previous_surname.name for previous_surname in rec.previous_surname_ids]) if rec.previous_surname_ids else ''
            surname = rec.surname_id.name if rec.surname_id else ''
            family = mother_maiden + ' ' + birth_surname + ' ' + previous_surname + ' ' + surname
            rec.family = family
    
            family_reverse = birth_surname + ' ' + surname + ' ' + mother_maiden
            
            prefix = " ".join([prefix.name for prefix in rec.prefix_ids]) if rec.prefix_ids else ''
            suffix = " ".join([suffix.name for suffix in rec.suffix_ids]) if rec.suffix_ids else ''
            
            if rec.display_order == 'first_maiden_last':
                full = prefix + ' ' + given + ' ' + family + ' ' + suffix
                rec.name = full
    
            if rec.display_order == 'maiden_last_first':
                full_reverse = prefix + ' ' + family + ' ' + given + ' ' + suffix
                rec.name = full_reverse
    
            if rec.display_order == 'first_last_maiden':
                full_family_reverse = prefix + ' ' + given + ' ' + family_reverse + ' ' + suffix
                rec.name = full_family_reverse
