### ISSUE TITLE
How to handle hierarchy with multiple parents

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#36]
For example,  `hc.vs.substance.code` found in `odoo-fhir/addons/hc_base/data/`

**Current code:** 

1. Model

Defined child and parent tables in `odoo-fhir/addons/hc_base/models/hc_value_set_contains.py`

```
class SubstanceCode(models.Model):  
    _name = "hc.vs.substance.code"  
    _description = "Substance Code"     
    _inherit = ["hc.value.set.contains"]    

    name = fields.Char(
        string="Name", 
        help="Name of this substance code.")
    code = fields.Char(
        string="Code", 
        help="Code of this substance code.")
    contains_id = fields.Many2one(
        comodel_name="hc.vs.substance.code",
        string="Parent", 
        help="Parent substance code.")

class ParentSubstanceCode(models.Model):    
    _name = "hc.parent.substance.code"  
    _description = "Parent Substance Code"          
    _inherit = ["hc.basic.association"] 
    _inherits = {"hc.vs.substance.code": "substance_code_id"}   

    substance_code_id = fields.Many2one(
        comodel_name="hc.vs.substance.code", 
        string="Substance Code", 
        ondelete="restrict", 
        required="True", 
        help="Substance Code associated with this Parent Substance Code.")                          

class SubstanceCode(models.Model):  
    _inherit = "hc.vs.substance.code"

    contains_ids = fields.Many2many(
        comodel_name="hc.parent.substance.code", 
        relation="substance_code_contains_rel", 
        string="Parents", 
        help="Parent substance code.")

```

2. Data Files

- parent file in `odoo-fhir/addons/hc_base/data/hc.parent.substance.code.csv`
Example parent substance:
Line 752: `hc_base.subs_code_410942007,"410942007","Drug or medicament","Drug or medicament (substance)"`
Line 781: `hc_base.subs_code_106181007,"106181007","Immunologic substance","Immunologic substance (substance)"`
Line 845: `hc_base.subs_code_373244000,"373244000","Immunologic agent","Immunologic agent (substance)"`

- child file in `odoo-fhir/addons/hc_base/data/hc.vs.substance.code.csv`

Example substance with multiple parents
Line 845: `hc_base.subs_code_373244000_hc_vs_substance_code,"hc_base.subs_code_410942007,hc_base.subs_code_106181007"`

3. Views

in `odoo-fhir/addons/hc_base/views/hc_substance_code_views.xml`

**Questions:**

1. Is using 2 models and 2 files the right approach?
2. Can this functionality be achieved with a single model?

**Comment by luigisison** [comment]
Tried today

For example,  `hc.vs.substance.code` found in `odoo-fhir/addons/hc_base/data/`

**Current code:** 

1. Model

Defined in `odoo-fhir/addons/hc_base/models/hc_res_substance.py`

```
class SubstanceCode(models.Model):  
    _name = "hc.vs.substance.code"  
    _description = "Substance Code"     
    _inherit = ["hc.value.set.contains"]    
...
    name = fields.Char(
        string="Name", 
        help="Name of this substance code.")
    code = fields.Char(
        string="Code", 
        help="Code of this substance code.")
    contains_id = fields.Many2one(
        comodel_name="hc.vs.substance.code",
        string="Parent", 
        help="Parent substance code.")
    parent_ids = fields.One2many(
        comodel_name="hc.vs.substance.code", 
        inverse_name="contains_id", 
        string="Parents", 
        help="Parent concept."
```

2. Data Files

In `odoo-fhir/addons/hc_base/hc_substance/hc.vs.substance.code.csv`

Substance has children (Allergen class, Biological substance, Drug or medicament)
Allergy class has 10 children
Biological substance has 1 child (Immunologic substance)
Immunologic substance has 1 child (Immunologic agent)
Drug or medicament has 1 child (Immunologic agent)

In other words, Immunologic agent has 2 parents (Immunlogic substance, Drug or medicament)

3. Views

in `odoo-fhir/addons/hc_substance/views/hc_substance_code_views.xml`

```
<record id="hc_vs_substance_code_view_form" model="ir.ui.view">
            <field name="name">Substance Code Form</field>                                                  
            <field name="model">hc.vs.substance.code</field>                                                    
            <field name="arch" type="xml">                                                  
...
                        <notebook>
                            <page string="Parents">                               
                                <field name="parent_ids" mode="tree">                         
                                    <tree>                      
                                        <field name="contains_id"/>
                                        <field name="child_level"/>                 
                                    </tree>
```

4. Error 

From tree view, select Substance record.
```
raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: hc.vs.substance.code(35940, 35941, 35942, 35943)
```

**Comment by BipinRathod** [comment]
parent_ids = fields.One2many(
        comodel_name="hc.vs.substance.code", 
        inverse_name="contains_id", 
        string="Parents", 
        help="Parent concept.")

    level_attributes = fields.Char('Level Attributes')

    parent_child_ids = fields.Many2many('hc.vs.substance.code', 'parent_child_rel','parent_id','child_id', string="Parents")

    @api.model
    def create(self, vals):
        res = super(SubstanceCode, self).create(vals)
        level_attr = False
        if res.parent_child_ids:
            for code in res.parent_child_ids:
                res.level = code.level + 1
                if not level_attr:
                    level_attr = '(' + str(res.level) + ',' + code.name +')'
                else:
                    level_attr = level_attr + ',' + '(' + str(res.level) + ',' + code.name +')'
        else:
            res.level = 0
        res.level_attributes = level_attr or ''
        return res

**Comment by luigisison** [comment]
Error:

```
ProgrammingError: column "hc_vs_substance_code_id" appears twice in unique constraint
LINE 1: ...NULL, "hc_vs_substance_code_id" INTEGER NOT NULL, UNIQUE("hc...
```

**Comment by luigisison** [comment]
Implemented:

```
    parent_child_ids = fields.Many2many(
        comodel_name="hc.vs.substance.code",
        relation="substance_code_parent_child_rel", 
        string="Parents", 
        help="Parent substance code.")
```

**Comment by luigisison** [comment]
Code to check for recursive relationships (e.g, A is a child of A)

**Comment by BipinRathod** [comment]
**Fixed Recursive issue**


@api.multi
    def write(self, vals):
        res = super(SubstanceCode, self).write(vals)
        for rec in self:
            if rec.parent_child_ids:
                if rec.id in rec.parent_child_ids.ids:
                    raise ValidationError("Recursive not possible")
        return res

**Comment by luigisison** [comment]
Desired behavior: Level Attribute of a child record is updated when a new parent is added.

Example:

AA and BBB are level 1 records.
CC is created.
AA is selected as a parent of CC. The `level_attribute` of CC is _(2,AA)_.
BB is selected as a parent of CC. The `level_attribute` of CC is updated to _(2,AA) , (2,BB)_

**Comment by luigisison** [comment]
Desired behavior: Calculate `level_attribute` after records have been imported.

**Comment by luigisison** [comment]
Issue: Can't import records from `hc.vs.substance.code.csv`

Layout: `"id","code","name","definition","contains_id/id","parent_child_ids/id","level","comments","source_id/id","system"`

Error:
```
 Unknown error during import: <type 'exceptions.ValueError'>: Expected singleton: hc.vs.substance.code(36160, 36161) at row 3
Resolve other errors first
Unknown error during import: <type 'exceptions.ValueError'>: Expected singleton: hc.vs.substance.code(36160, 36161, 36162) at row 4
Resolve other errors first
Unknown error during import: <type 'exceptions.ValueError'>: Expected singleton: hc.vs.substance.code(36160, 36161, 36162, 36163) at row 5
Resolve other errors first
No matching record found for external id 'hc_substance.subs_code_406455002' in field 'Parents' at row 6
Get all possible values
(9 more) 
```

Workaround: 
Import records except `"contains_id/id","parent_child_ids/id"`
Import records again with `"contains_id/id","parent_child_ids/id"`

**Comment by luigisison** [comment]
Restart server. Code works!
