### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by lasley** [luigisison/odoo-fhir#37]
Excellent repo you have here! I don't see any licensing though, would you mind adding one? 

A repo without a license means that it cannot be used in any way without explicit permission from the copyright holders, in writing. Adding a license will let everyone know the terms in which they may use your code, which will increase adoption rate. OCA recommends either LGPL-3, GPL-3, or AGPL-3 just depending on your needs. [This is a good breakdown of them, plus some others](https://choosealicense.com/licenses/).

My recommended is LGPL-3, because it does not force licensing upon code which is using it as a library (`depends` key of Odoo manifest). This comes with some possible ramifications though, because now someone can package and sell a product including your code (a great example is MacOS and iOS). 

GPL-3 is basically LGPL-3, but it forces the GPL-3 license on any code depending on it. AGPL-3 is GPL-3, but it redefines "distribution" to include network use (closing a loophole in GPL-3 usage on SaaS platforms).

For a frame of reference, [Vertical Medical](https://github.com/oca/vertical-medical) was AGPL-3, and is in the process of moving towards primarily LGPL-3.

**Comment by lasley** [comment]
[Here's OCA's FAQ too](https://odoo-community.org/page/faq#docs-internal-guid-eb42b519-45ad-c62b-db60-4305d8b7d610)

**Comment by luigisison** [comment]
Posted AGPLv3 license.
