### ISSUE TITLE
Compatibility With CI

### ISSUE THREAD

**Issue by lasley** [luigisison/odoo-fhir#38]
I would like to make this repo compatible with CI, but the file hierarchy is not compatible. I made the change and was going to submit a PR, but then realized this would basically make it look like I made all these files. 

Take a look here - https://github.com/luigisison/odoo-fhir/compare/master...LasLabs:hotfix/ci-compat

Basically all you need to do though is remove the `custom/addons/database_cleanup` folder, then move everything in the `addons` folder into the root of the repo instead. I'll submit a PR after your's is merged in order to finalize the CI setup.

**Comment by luigisison** [comment]
What is CI?

Can't make sense of the example. Can you send me another example of the layout you are requesting?

**Comment by luigisison** [comment]
I need` database_cleanup`. If I remove it, how can I use it?

**Comment by lasley** [comment]
> What is CI?

CI is continuous integration - for tests before merging. We use [TravisCI](https://travis-ci.org/) and [Runbot](https://runbot.odoo-community.org/).

> Can't make sense of the example. Can you send me another example of the layout you are requesting?

Just take a look at any of the OCA repos. An addons repo should contain its addons directly in its root, instead of subdirectories. It is not compatible with Odoo otherwise, which does not scan recursively into addons directories. You're going for a hierarchy like this:

/hc_account
/hc_activity_definition
/hc_adverse_event

instead of

/addons/hc_account
/addons/hc_activity_definition
/addons/hc_adverse_event

> I need database_cleanup. If I remove it, how can I use it?

This is an OCA addon - you should just clone the repo locally and add it in the addons section of your Odoo configuration, restart Odoo, then rescan modules via the apps menu.

We use an automation file for continuous integration to build against the dependencies as well. I will add that in a pull request once the repo is compatible from a layout perspective.

**Comment by luigisison** [comment]
For future
