### ISSUE TITLE
Preferred Name for a Person

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#41]
Desired behaviors:

1. When a new **Person** record is created and a **Human Name** is selected, the **Human Name** is also entered in the `Person.Name` table with the `is_preferred = True`.

2. When a **Human Name** is added to an existing **Person** record and the new **Human Name** is marked as **preferred**, then two changes occur:
a. The original **Human Name** which was **preferred** is now **not preferred**.
b. The **Human Name** of the **Person** is changed to the new preferred **Human Name**.

3. When a **Person** has several **Human Names**, one and only one of the names is **preferred**.

4. When a **Person** has several **Human Names**, and one of the **Human Name** is changed to **preferred**, then the behavior of 2a and 2b occur.

**Comment by BipinRathod** [comment]
@api.model
    def create(self, vals):
        person_name_obj = self.env['hc.person.name']
        name = self.env['hc.human.name'].browse(vals['name_id'])
        vals['name'] = name.name
        names_vals = {}
        res = super(Person, self).create(vals)
        if name:
            names_vals.update({
                        'is_preferred': True,
                        'human_name_id': name.id,
                        'person_id': res.id
                        })
            person_name_obj.create(names_vals)
            
        # vals['is_patient'] = self.env.context.get('is_patient', False)
        # vals['is_practitioner'] = self.env.context.get('is_practitioner', False)
        # vals['is_related_person'] = self.env.context.get('is_related_person', False)
        return res

**Comment by BipinRathod** [comment]
@api.model
    def create(self, vals):
        person_obj = self.env['hc.res.person']
        if vals and vals.get('is_preferred'):
            person_ids = self.search([('person_id','=',vals.get('person_id'))])
            for person in person_ids:
                person.is_preferred = False
        res = super(PersonName, self).create(vals)
        return res

**Comment by BipinRathod** [comment]
@api.multi
    def write(self, vals):
        if vals and vals.get('is_preferred'):
            person_ids = self.search([('person_id','=',self.person_id.id),('id','!=',self.id)])
            for person in person_ids:
                person.is_preferred = False
        return super(PersonName, self).write(vals)

**Comment by BipinRathod** [comment]
**Object : PersonName**


    @api.model
    def create(self, vals):
        person_obj = self.env['hc.res.person']
        if vals and vals.get('is_preferred'):
            person_ids = self.search([('person_id','=',vals.get('person_id'))])
            for person in person_ids:
                person.is_preferred = False
        return super(PersonName, self).create(vals)

    @api.multi
    def write(self, vals):
        if vals and vals.get('is_preferred'):
            person_ids = self.search([('person_id','=',self.person_id.id),('id','!=',self.id)])
            for person in person_ids:
                person.is_preferred = False
        return super(PersonName, self).write(vals)

**Comment by luigisison** [comment]
It works!
