### ISSUE TITLE
How to define Default Date to Today

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#45]
Current code:

In `hc_annotation.py`,

```
from openerp import models, fields, api
from datetime import datetime
from openerp.tools import DEFAULT_SERVER_DATETIME_FORMAT as DTF

Class Annotation(models.AbstractModel):
    _name = "hc.annotation"
...
    recorded_date = fields.Datetime(
        string="Recorded Date",
        default="_get_default_date", 
        help="When the annotation was made.")

    def _get_default_date(self):
        return datetime.strftime(datetime.strptime(date.today(), DTF), "%Y-%m-%d %H:%M:%S")
```

Error:
`ValueError: time data '_get_default_date' does not match format '%Y-%m-%d %H:%M:%S`'

Desired behavior:

recorded_date = date.today()

**Comment by BipinRathod** [comment]
def _get_default_date(self):
        return datetime.strftime(datetime.strptime(date.today(), DTF), DTF)

or 

def _get_default_date(self):
        return datetime.strptime(date.today(), DTF)

**Comment by luigisison** [comment]
Implemented: `default=fields.datetime.now()`
