### ISSUE TITLE
1 Track Allergy Intolerance Clinical Status History

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#46]
Desired behavior: Track changes in `clinical_status` in `hc.allergy.intolerance.clinical.status.history`

- Initial record in `hc.allergy.intolerance.clinical.status.history`
```
clinical_status = hc_res_allergy_intolerance.clinical_status
start_date = asserted_date
end_date = revised asserted_date or datetime.now() whichever is later
```

- Subsequent record in `hc.allergy.intolerance.clinical.status.history`
```
clinical_status = revised hc_res_allergy_intolerance.clinical_status
start_date = end_date of initial record
end_date = revised asserted_date or datetime.now() whichever is later

```
Current code:

```
class AllergyIntolerance(models.Model): 
    _name = "hc.res.allergy.intolerance"    
    _description = "Allergy Intolerance"
...
    clinical_status = fields.Selection(
        string="Clinical Status", 
        required="True", 
        selection=[
            ("draft", "Draft"), 
            ("active", "Active"), 
            ("resolved", "Resolved")],
        default="draft", 
        help="The clinical status of the allergy or intolerance.")
    clinical_status_history_ids = fields.One2many(
        comodel_name="hc.allergy.intolerance.clinical.status.history", 
        inverse_name="allergy_intolerance_id", 
        string="Clinical Status History", 
        help="The clinical status of the allergy or intolerance over time.")

class AllergyIntoleranceClinicalStatusHistory(models.Model):
    _name = "hc.allergy.intolerance.clinical.status.history"
    _description = "Allergy Intolerance Clinical Status History"

    allergy_intolerance_id = fields.Many2one(
        comodel_name="hc.res.allergy.intolerance", 
        string="Allergy Intolerance", 
        help="Allergy Intolerance associated with this Allergy Intolerance Clinical Status History.")                                
    clinical_status = fields.Char(
        string="Clinical Status", 
        compute="_compute_clinical_status_history", 
        store="True", 
        help="The clinical status of the allergy or intolerance.")
    start_date = fields.Date(
        string="Start Date", 
        help="Start of the period during which this clinical status is valid.")        
    end_date = fields.Date(
        string="End Date", 
        help="End of the period during which this clinical status is valid.")
```

**Comment by BipinRathod** [comment]
@api.model
    def create(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).create(vals)
        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': res.id,
                        'clinical_status': res.clinical_status,
                        'start_date': datetime.today()
                        }
            clinical_status_history_obj.create(history_vals)
        return res

    @api.multi
    def write(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).write(vals)
        clinical_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        if clinical_history_record_ids:
            for clinical_history in clinical_history_record_ids:
                clinical_history.end_date = datetime.strftime(datetime.today(), DTF)
#                time_diff = datetime.today() - datetime.strptime(clinical_history.start_date, DTF)
#                if time_diff:
#                    clinical_history.time_diff_days = str(time_diff.days)
#                    clinical_history.time_diff_hours = str(time_diff.min / 60)
#                    clinical_history.time_diff_mins = str(time_diff.min)
#                    clinical_history.time_diff_sec = str(time_diff.seconds)
        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': self.id,
                        'clinical_status': vals.get('clinical_status'),
                        'start_date': datetime.today(),
                        }
            clinical_status_history_obj.create(history_vals)
        return res

**Comment by BipinRathod** [comment]
@api.model
    def create(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).create(vals)
        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': res.id,
                        'clinical_status': res.clinical_status,
                        'start_date': datetime.today()
                        }
            clinical_status_history_obj.create(history_vals)
        return res

    @api.multi
    def write(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).write(vals)
        clinical_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        if clinical_history_record_ids:
            for clinical_history in clinical_history_record_ids:
                clinical_history.end_date = datetime.strftime(datetime.today(), DTF)
        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': self.id,
                        'clinical_status': vals.get('clinical_status'),
                        'start_date': datetime.today(),
                        }
            clinical_status_history_obj.create(history_vals)
        return res
