### ISSUE TITLE
Calculate duration of Clinical Status

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#49]
Duration = end_date - start_date expressed in hours, minutes, seconds

**Comment by BipinRathod** [comment]
@api.multi
    def write(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).write(vals)
        clinical_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        if clinical_history_record_ids:
            for clinical_history in clinical_history_record_ids:
                clinical_history.end_date = datetime.strftime(datetime.today(), DTF)
                time_diff = datetime.today() - datetime.strptime(clinical_history.start_date, DTF)
                if time_diff:
                    days = str(time_diff).split(',')
                    times = str(days[1]).split(':')
                    clinical_history.time_diff_days = str(days[0])
                    clinical_history.time_diff_hours = str(times[0])
                    clinical_history.time_diff_mins = str(times[1])
                    clinical_history.time_diff_sec = str(times[2])

**Comment by luigisison** [comment]
Error:

```
  File "/odoo/odoo-fhir/addons/hc_allergy_intolerance/models/hc_res_allergy_intolerance.py", line 408, in write
    res = super(AllergyIntolerance, self).write(vals)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by luigisison** [comment]
Error:

```
   File "/odoo/odoo-fhir/addons/hc_allergy_intolerance/models/hc_res_allergy_intolerance.py", line 280, in write
    times = str(days[1]).split(':')
IndexError: list index out of range
```

**Comment by BipinRathod** [comment]
@api.multi
    def write(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).write(vals)
        clinical_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        if clinical_history_record_ids:
            for clinical_history in clinical_history_record_ids:
                clinical_history.end_date = datetime.strftime(datetime.today(), DTF)
                time_diff = datetime.today() - datetime.strptime(clinical_history.start_date, DTF)
                if time_diff:
                    days = str(time_diff).split(',')
                    if len(days) > 1:
                        times = str(days[1]).split(':')
                        clinical_history.time_diff_days = str(days[0])
                    else:
                        times = str(time_diff).split(':')
                        if times:
                            clinical_history.time_diff_hours = str(times[0])
                            clinical_history.time_diff_mins = str(times[1])
                            clinical_history.time_diff_sec = str(times[2])

        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': self.id,
                        'clinical_status': vals.get('clinical_status'),
                        'start_date': datetime.today(),
                        }
            clinical_status_history_obj.create(history_vals)
        return res

**Comment by BipinRathod** [comment]
**Improved code for Calculate duration**


    @api.multi
    def write(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).write(vals)
        clinical_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        if clinical_history_record_ids:
            for clinical_history in clinical_history_record_ids:
                clinical_history.end_date = datetime.strftime(datetime.today(), DTF)
                time_diff = datetime.today() - datetime.strptime(clinical_history.start_date, DTF)
                if time_diff:
                    days = str(time_diff).split(',')
                    if days and len(days) > 1:
                        clinical_history.time_diff_days = str(days[0])
                        times = str(days[1]).split(':')
                        if times and times > 1:
                            clinical_history.time_diff_hours = str(times[0])
                            clinical_history.time_diff_mins = str(times[1])
                            clinical_history.time_diff_sec = str(times[2])
                    else:
                        times = str(time_diff).split(':')
                        if times and times > 1:
                            clinical_history.time_diff_hours = str(times[0])
                            clinical_history.time_diff_mins = str(times[1])
                            clinical_history.time_diff_sec = str(times[2])

        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': self.id,
                        'clinical_status': vals.get('clinical_status'),
                        'start_date': datetime.today(),
                        }
            clinical_status_history_obj.create(history_vals)
        return res

**Comment by luigisison** [comment]
changed `clinical_history` to `clinical_status_history`.

Error: 
"File "/odoo/odoo-fhir/addons/hc_allergy_intolerance/models/hc_res_allergy_intolerance.py", line 260, in write
    time_diff = datetime.today() - datetime.strptime(clinical_status_history.start_date, DTF)
UnboundLocalError: local variable 'clinical_status_history' referenced before assignment"

**Comment by luigisison** [comment]
How to calculate duration of verification status?

**Comment by luigisison** [comment]
Changed `clinical_history` to `clinical_status_history`

Caused Error:
 ```
File "/odoo/odoo-fhir/addons/hc_allergy_intolerance/models/hc_res_allergy_intolerance.py", line 260, in write
    time_diff = datetime.today() - datetime.strptime(clinical_status_history.start_date, DTF)
UnboundLocalError: local variable 'clinical_status_history' referenced before assignment
```

**Comment by luigisison** [comment]
My code now:

```
    @api.model
    def create(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        res = super(AllergyIntolerance, self).create(vals)
        if vals and vals.get('clinical_status'):
            history_vals = {
                'allergy_intolerance_id': res.id,
                'clinical_status': res.clinical_status,
                'start_date': datetime.today()
                }
            clinical_status_history_obj.create(history_vals)
        return res

    @api.multi                  
    def write(self, vals):                  
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']                
        res = super(AllergyIntolerance, self).write(vals)               
        clinical_status_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])              
        if clinical_status_history_record_ids:              
            for clinical_status_history in clinical_status_history_record_ids:          
                clinical_status_history.end_date = datetime.strftime(datetime.today(), DTF)     
        time_diff = datetime.today() - datetime.strptime(clinical_status_history.start_date, DTF)               
        if time_diff:               
            days = str(time_diff).split(',')            
            if len(days) > 1:           
                times = str(days[1]).split(':')     
                clinical_status_history.time_diff_day = str(days[0])        
            else:           
                times = str(time_diff).split(':')       
                if times:       
                    clinical_status_history.time_diff_hour = str(times[0])  
                    clinical_status_history.time_diff_min = str(times[1])   
                    clinical_status_history.time_diff_sec = str(times[2])   
                        
        if vals and vals.get('clinical_status'):                
            history_vals = {            
                'allergy_intolerance_id': self.id,      
                'clinical_status': vals.get('clinical_status'),     
                'start_date': datetime.today()      
                }       
            clinical_status_history_obj.create(history_vals)            
        return res
```

**Comment by BipinRathod** [comment]
**Updated Code**


    @api.model
    def create(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        verification_status_history_obj = self.env['hc.allergy.intolerance.verification.status.history']
        res = super(AllergyIntolerance, self).create(vals)

        #clinical_status
        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': res.id,
                        'clinical_status': res.clinical_status,
                        'start_date': datetime.today()
                        }
            clinical_status_history_obj.create(history_vals)

        #Code for Verification Status
        if vals and vals.get('verification_status'):
            verification_status_history_vals = {
                        'allergy_intolerance_id': res.id,
                        'verification_status': res.verification_status,
                        'start_date': datetime.today()
                        }
            verification_status_history_obj.create(verification_status_history_vals)
        return res

    @api.multi
    def write(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        verification_status_history_obj = self.env['hc.allergy.intolerance.verification.status.history']
        res = super(AllergyIntolerance, self).write(vals)
        clinical_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        verification_status_history_ids = verification_status_history_obj.search([('end_date','=', False)])
        if clinical_history_record_ids:
            for clinical_history in clinical_history_record_ids:
                clinical_history.end_date = datetime.strftime(datetime.today(), DTF)
                time_diff = datetime.today() - datetime.strptime(clinical_history.start_date, DTF)
                if time_diff:
                    days = str(time_diff).split(',')
                    if days and len(days) > 1:
                        clinical_history.time_diff_days = str(days[0])
                        times = str(days[1]).split(':')
                        if times and times > 1:
                            clinical_history.time_diff_hours = str(times[0])
                            clinical_history.time_diff_mins = str(times[1])
                            clinical_history.time_diff_sec = str(times[2])
                    else:
                        times = str(time_diff).split(':')
                        if times and times > 1:
                            clinical_history.time_diff_hours = str(times[0])
                            clinical_history.time_diff_mins = str(times[1])
                            clinical_history.time_diff_sec = str(times[2])

        if verification_status_history_ids:
            for verification_status_history in verification_status_history_ids:
                verification_status_history.end_date = datetime.strftime(datetime.today(), DTF)
                time_diff = datetime.today() - datetime.strptime(verification_status_history.start_date, DTF)
                if time_diff:
                    days = str(time_diff).split(',')
                    if days and len(days) > 1:
                        verification_status_history.time_diff_days = str(days[0])
                        times = str(days[1]).split(':')
                        if times and times > 1:
                            verification_status_history.time_diff_hours = str(times[0])
                            verification_status_history.time_diff_mins = str(times[1])
                            verification_status_history.time_diff_sec = str(times[2])
                    else:
                        times = str(time_diff).split(':')
                        if times and times > 1:
                            verification_status_history.time_diff_hours = str(times[0])
                            verification_status_history.time_diff_mins = str(times[1])
                            verification_status_history.time_diff_sec = str(times[2])
        if vals and vals.get('clinical_status'):
            history_vals = {
                        'allergy_intolerance_id': self.id,
                        'clinical_status': vals.get('clinical_status'),
                        'start_date': datetime.today(),
                        }
            clinical_status_history_obj.create(history_vals)

        if vals and vals.get('verification_status'):
            verification_status_history_vals = {
                        'allergy_intolerance_id': self.id,
                        'verification_status': vals.get('verification_status'),
                        'start_date': datetime.today()
                        }
            verification_status_history_obj.create(verification_status_history_vals)
        return res


**Added fields in AllergyIntoleranceVerificationStatusHistory Model**


    time_diff_days = fields.Char(string='Time Diff.(Days)')
    time_diff_hours = fields.Char(string='Time Diff.(Hours)')
    time_diff_mins = fields.Char(string='Time Diff.(Mins)')
    time_diff_sec = fields.Char(string='Time Diff.(Sec.)')


**Added fields in View too**

<page string="Verification Statuses">
                                <field name="verification_status_history_ids" mode="tree">
                                    <tree>
                                        <field name="verification_status" readonly="1"/>
                                        <field name="start_date" readonly="1"/>
                                        <field name="end_date" readonly="1"/>
                                        <field name="write_uid"/>
                                        <field name="time_diff_days"/>
                                        <field name="time_diff_hours"/>
                                        <field name="time_diff_mins"/>
                                        <field name="time_diff_sec"/>
                                    </tree>
                                </field>
                            </page>

**Comment by luigisison** [comment]
Add: If `clinical_status` does not change, don't calculate` end_date`.
Add: If `verification_status` does not change, don't calculate` end_date`.

**Comment by BipinRathod** [comment]
**Updated Code, its only update if the status change respective clinical or verification**
    @api.multi
    def write(self, vals):
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        verification_status_history_obj = self.env['hc.allergy.intolerance.verification.status.history']
        res = super(AllergyIntolerance, self).write(vals)
        clinical_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        verification_status_history_ids = verification_status_history_obj.search([('end_date','=', False)])
        if clinical_history_record_ids:
            if vals.get('clinical_status') and clinical_history_record_ids[0].clinical_status != vals.get('clinical_status'):
                for clinical_history in clinical_history_record_ids:
                    clinical_history.end_date = datetime.strftime(datetime.today(), DTF)
                    time_diff = datetime.today() - datetime.strptime(clinical_history.start_date, DTF)
                    if time_diff:
                        days = str(time_diff).split(',')
                        if days and len(days) > 1:
                            clinical_history.time_diff_days = str(days[0])
                            times = str(days[1]).split(':')
                            if times and times > 1:
                                clinical_history.time_diff_hours = str(times[0])
                                clinical_history.time_diff_mins = str(times[1])
                                clinical_history.time_diff_sec = str(times[2])
                        else:
                            times = str(time_diff).split(':')
                            if times and times > 1:
                                clinical_history.time_diff_hours = str(times[0])
                                clinical_history.time_diff_mins = str(times[1])
                                clinical_history.time_diff_sec = str(times[2])
                history_vals = {
                        'allergy_intolerance_id': self.id,
                        'clinical_status': vals.get('clinical_status'),
                        'start_date': datetime.today(),
                        }
                clinical_status_history_obj.create(history_vals)
        if verification_status_history_ids:
            if vals.get('verification_status') and verification_status_history_ids[0].verification_status != vals.get('verification_status'):
                for verification_status_history in verification_status_history_ids:
                    verification_status_history.end_date = datetime.strftime(datetime.today(), DTF)
                    time_diff = datetime.today() - datetime.strptime(verification_status_history.start_date, DTF)
                    if time_diff:
                        days = str(time_diff).split(',')
                        if days and len(days) > 1:
                            verification_status_history.time_diff_days = str(days[0])
                            times = str(days[1]).split(':')
                            if times and times > 1:
                                verification_status_history.time_diff_hours = str(times[0])
                                verification_status_history.time_diff_mins = str(times[1])
                                verification_status_history.time_diff_sec = str(times[2])
                        else:
                            times = str(time_diff).split(':')
                            if times and times > 1:
                                verification_status_history.time_diff_hours = str(times[0])
                                verification_status_history.time_diff_mins = str(times[1])
                                verification_status_history.time_diff_sec = str(times[2])
                verification_status_history_vals = {
                            'allergy_intolerance_id': self.id,
                            'verification_status': vals.get('verification_status'),
                            'start_date': datetime.today()
                            }
                verification_status_history_obj.create(verification_status_history_vals)
        return res

**Comment by luigisison** [comment]
Added after `if clinical_status_history_record_ids:`

`if vals.get('clinical_status') and clinical_status_history_record_ids[0].clinical_status != vals.get('clinical_status'):`

Added at end of `if clinical_status_history_record_ids:`
```
                clinical_status_history_vals = {            
                    'allergy_intolerance_id': self.id,      
                    'clinical_status': vals.get('clinical_status'),     
                    'start_date': datetime.today()      
                    }       
                clinical_status_history_obj.create(clinical_status_history_vals)
```

Added after `if verification_status_history_record_ids:`

` if vals.get('verification_status') and verification_status_history_record_ids[0].verification_status != vals.get('verification_status'):`

Added at end of `if verification_status_history_record_ids:`
```
                verification_status_history_vals = {    
                    'allergy_intolerance_id': self.id,
                    'verification_status': vals.get('verification_status'),
                    'start_date': datetime.today()
                    }
                verification_status_history_obj.create(verification_status_history_vals)
```
