### ISSUE TITLE
Display Person Name and Birth Date in Dropdown

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#51]
Model: `hc_res_patient.py`, 

Desired behavior: When creating a `Patient`, show `Person Name` and `Birth Date` in dropdown to distinguish between two Persons with the same name.

**Comment by BipinRathod** [comment]
**Model : Person**


    @api.model
    def name_search(self, name='', args=None, operator='ilike', limit=100):
        context = dict(self._context)
        if context is None:
            context = {}
        if args is None:
            args = []
        if not operator:
            operator = 'ilike'
        if name:
                args.append(('name_id', operator, name))
        ids = self.search(args, limit=limit)
        name_rec = []
        for id in ids:
            if id.birth_date:
                name_rec.append((id.id, id.name_id.name + "("+id.birth_date+")"))
            else:
                name_rec.append((id.id, id.name_id.name))
        return name_rec
