### ISSUE TITLE
Constraints: Allergy Intolerance

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#58]
If `verification_status` is not **entered-in-error**, then `clinical_status` is **required**. (ref: ait-1)

If` verification_status` = **entered-in-error**, then `clinical_status` is **empty**. (ref: ait-2)

**Comment by luigisison** [comment]
Code:

 ```
   class AllergyIntolerance(models.Model): 
    _name = "hc.res.allergy.intolerance"
...
    clinical_status = fields.Selection(
        string="Clinical Status", 
        required="True", 
        selection=[
            ("draft", "Draft"), 
            ("active", "Active"), 
            ("resolved", "Resolved")],
        default="draft", 
        help="The clinical status of the allergy or intolerance.")

    verification_status = fields.Selection(
        string="Verification Status", 
        required="True", 
        selection=[
            ("unconfirmed", "Unconfirmed"), 
            ("confirmed", "Confirmed"), 
            ("refuted", "Refuted"), 
            ("entered-in-error", "Entered-In-Error")],
        default="unconfirmed", 
        help="Assertion about certainty associated with the propensity, or potential risk, of a reaction to the identified substance (including pharmaceutical product).")
```

**Comment by luigisison** [comment]
Add to view:

<field name="clinical_status" attrs="{'required': [('verification_status','in',['unconfirmed','confirmed','refuted'])], 'invisible': [('verification_status','=','entered-in-error')]}"/>

**Comment by luigisison** [comment]
Issue: When `verification_status = entered-in-error`, status record is not created.

**Comment by BipinRathod** [comment]
**Obj = 'hc.res.allergy.intolerance'**


    @api.multi                  
    def write(self, vals):                  
        clinical_status_history_obj = self.env['hc.allergy.intolerance.clinical.status.history']
        verification_status_history_obj = self.env['hc.allergy.intolerance.verification.status.history']                
        res = super(AllergyIntolerance, self).write(vals)               

        # For Verification Status
        verification_status_history_record_ids = verification_status_history_obj.search([('end_date','=', False)])
        if verification_status_history_record_ids:
            if vals.get('verification_status') and verification_status_history_record_ids[0].verification_status != vals.get('verification_status'):
                for verification_status_history in verification_status_history_record_ids:
                    verification_status_history.end_date = datetime.strftime(datetime.today(), DTF)              
                    time_diff = datetime.today() - datetime.strptime(verification_status_history.start_date, DTF)               
                    if time_diff:               
                        days = str(time_diff).split(',')            
                        if days and len(days) > 1:          
                            verification_status_history.time_diff_day = str(days[0])        
                            times = str(days[1]).split(':')     
                            if times and times > 1:     
                                verification_status_history.time_diff_hour = str(times[0])  
                                verification_status_history.time_diff_min = str(times[1])   
                                verification_status_history.time_diff_sec = str(times[2])   
                        else:                       
                            times = str(time_diff).split(':')       
                            if times and times > 1:     
                                verification_status_history.time_diff_hour = str(times[0])  
                                verification_status_history.time_diff_min = str(times[1])   
                                verification_status_history.time_diff_sec = str(times[2])   
                verification_status_history_vals = {    
                    'allergy_intolerance_id': self.id,
                    'verification_status': vals.get('verification_status'),
                    'start_date': datetime.today()
                    }
                if vals.get('verification_status') == 'entered-in-error':
                    verification_status_history_vals.update({'end_date': datetime.today()})
                verification_status_history_obj.create(verification_status_history_vals)    
          
        # For Clinical Status
        clinical_status_history_record_ids = clinical_status_history_obj.search([('end_date','=', False)])
        if clinical_status_history_record_ids:
            if vals.get('verification_status') == 'entered-in-error' or (vals.get('clinical_status') and clinical_status_history_record_ids[0].clinical_status != vals.get('clinical_status')):            
                
                for clinical_status_history in clinical_status_history_record_ids:          
                    clinical_status_history.end_date = datetime.strftime(datetime.today(), DTF)     
                    time_diff = datetime.today() - datetime.strptime(clinical_status_history.start_date, DTF)               
                    if time_diff:               
                        days = str(time_diff).split(',')            
                        if days and len(days) > 1:             
                            clinical_status_history.time_diff_day = str(days[0])
                            times = str(days[1]).split(':')
                            if times and times > 1:
                                clinical_status_history.time_diff_hour = str(times[0])
                                clinical_status_history.time_diff_min = str(times[1])
                                clinical_status_history.time_diff_sec = str(times[2])        
                        else:           
                            times = str(time_diff).split(':')       
                            if times and times > 1:      
                                clinical_status_history.time_diff_hour = str(times[0])  
                                clinical_status_history.time_diff_min = str(times[1])   
                                clinical_status_history.time_diff_sec = str(times[2])
                    clinical_status_history_vals = {            
                        'allergy_intolerance_id': self.id,      
                        'clinical_status': vals.get('clinical_status'),     
                        'start_date': datetime.today()      
                        }
                    if vals.get('verification_status') == 'entered-in-error':
                        clinical_status_history_vals.update({'end_date': datetime.today()})
                    if vals.get('verification_status') != 'entered-in-error':
                        clinical_status_history_obj.create(clinical_status_history_vals)
        else:
            clinical_status_history_vals = {            
                    'allergy_intolerance_id': self.id,      
                    'clinical_status': vals.get('clinical_status'),     
                    'start_date': datetime.today()      
                    }       
            if vals.get('verification_status') == 'entered-in-error':
                    clinical_status_history_vals.update({'end_date': datetime.today()})
            clinical_status_history_obj.create(clinical_status_history_vals)
        return res

**Comment by luigisison** [comment]
Test 1 - Pass
- Create a new record 
- Set `verification_status` = entered-in-error
- Outcomes

1. **Verification Status History** record created with `verification_status` = entered-in-error, `start_date` = datetime.today(), `end_date`=datetime.today()
2. No **Clinical Status History** record created.

Test 2 - Pass
- Create a new record 
- Set `verification_status` = unconfirmed
- Set `clinical_status` = draft
- Outcomes

1. **Verification Status History** record created with `verification_status` = unconfirmed, `start_date` = datetime.today(), no `end_date`
2. **Clinical Status History** record created with `clinical_status` = draft, `start_date` = datetime.today(), no `end_date`

Test 3 - Fail
- Edit record
- Change `clinical_status` = active
- Outcomes

1. Pass - **Verification Status History** record created with `verification_status` = unconfirmed, `start_date` = datetime.today(), no `end_date`
2. Pass - **Clinical Status History** record created with `clinical_status` = active, `start_date` = datetime.today(), no `end_date`
3. Pass - **Clinical Status History** record with `clinical_status` = draft `end_date` = datetime.today(), **Time Diff** calculated
4. Fail - Many **Clinical Status History** records with `clinical_status` = active are created.
5. Pass - **Verification Status History** record not changed

Test 4 - Fail
- Edit record
- Change `verification_status` = confirmed
- Outcomes

1. Fail - **Verification Status History** record not changed. New record not created
2. Pass - **Clinical Status History** record not changed

Test 5 - Pass
- Edit record
- Change `verification_status` = entered-in-error
- Outcomes

1. Pass - **Verification Status History** record with `verification_status` = unconfirmed `end_date` = datetime.today(), **Time Diff** calculated. 
2. Pass - **Verification Status History** record with `verification_status` = entered-in-error `start_date` = `end_date` = datetime.today(), **Time Diff** calculated
2. Pass - **Clinical Status History** record `end_date` = datetime.today(), **Time Diff** calculated.
