### ISSUE TITLE
Create PDF Report: Allergy Intolerance Observation

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#84]

**Comment by luigisison** [comment]
Create report folder: 

`sudo mkdir   /odoo/odoo-fhir/addons/hc_allergy_intolerance/report`

**Comment by BipinRathod** [comment]
'data': [
        'report/allergy_intolerance_report_template.xml',
        'report/report_view.xml'
    ],

**Comment by luigisison** [comment]
Code for many2many field `manifestation_ids`

**Comment by luigisison** [comment]
<odoo>

    
    <template id="report_allergy_intolerance_observation">
        <t>
            <t t-call="report.external_layout">
                <t t-foreach="docs" t-as="o">
                    <div class="page">
                        <table width="100%">
                            <tr>
                                <td>
                                    <center>
                                        <h2>
                                            <b>Allergy Intolerance Observation</b>
                                        </h2>
                                    </center>
                                </td>
                            </tr>
                        </table>
                        <br/>
                        <table class="table table-condensed">
                            <thead>
                                <tr style="color:blue; size:4">
                                    <td width="50%">
                                        <b>Event</b>
                                    </td>
                                    <td width="50%">
                                        <b>Status</b>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td width="50%">
                                        <b>Patient Name: </b><span t-field="o.patient_id.name"/>
                                    </td>
                                    <td width="50%">
                                        <b>Verification Status: </b><span t-field="o.verification_status"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%">
                                        <b>Allergy/Intolerance: </b><span t-field="o.code_id.name"/>
                                    </td>
                                    <td width="50%">
                                        <b>Clinical Status: </b><span t-field="o.clinical_status"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%">
                                        <b>Asserted Date: </b><span t-field="o.asserted_date"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%">
                                        <b>Type: </b><span t-field="o.type"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%">
                                        <b>Criticality: </b><span t-field="o.criticality"/>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <br/>
                        <table class="table table-condensed">
                            <thead>
                                <tr style="color:blue; size:4">
                                    <td width="50%">
                                        <b>Who, Where</b>
                                    </td>
                                    <td width="50%">
                                        <b>Timeline</b>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td width="50%" style="border:None">
                                        <b>Recorder: </b><span t-field="o.recorder_name"/>
                                    </td>
                                    <td width="50%" style="border:None">
                                        <b>Onset: </b><span t-field="o.onset_name"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Asserter: </b><span t-field="o.asserter_name"/>
                                    </td>
                                    <td width="50%">
                                        <b>Last Occurence Date: </b><span t-field="o.last_occurence"/>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <br/>
                        <table class="table table-condensed">
                            <tr>
                                 <td style="color:blue">
                                    <h3>
                                        <b>Reactions</b>
                                    </h3>
                                </td>
                            </tr>
                            
                        </table>
                        <table class="table table-condensed" t-foreach="o.reaction_ids" t-as="reaction">
                            <thead>
                                <tr style="color:blue; size:4">
                                    <td>
                                        <b>Substance: </b><span t-field="reaction.substance_id.name"/>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td width="50%">
                                        <b>Description: </b><span t-field="reaction.description"/>
                                    </td>
                                    <td width="50%">
                                        <b>Severity: </b><span t-field="reaction.severity"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%">
                                        <b>Onset: </b><span t-field="reaction.onset"/>
                                    </td>
                                    <td width="50%">
                                        <b>Certainty: </b><span t-field="reaction.certainty"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%">
                                        <b>Duration: </b><span t-field="reaction.duration"/>
                                    </td>
                                    <td width="50%">
                                        <b>Manifestations: </b><span t-field="reaction.manifestation_ids.name"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%">
                                        <b>Duration UOM: </b><span t-field="reaction.duration_uom_id.name"/>
                                    </td>
                                    <td width="50%">
                                        <b>Exposure Route: </b><span t-field="reaction.exposure_route_id.name"/>
                                    </td>
                                </tr>
                            </tbody>
                            <table class="table table-condensed" t-foreach="o.note_ids" t-as="note">
                                <tr>
                                    <td>
                                        <b>Text: </b><span t-field="note.text"/>
                                    </td>
                                </tr>
                            </table>
                        </table>
                    </div>
                </t>
            </t>
        </t>
    </template>

</odoo>

**Comment by luigisison** [comment]
`hc_res_allergy_intolerance_report_views.xml`

```
<odoo>

    <report id="action_report_allergy_intolerance_observation"
            model="hc.res.allergy.intolerance"
            string="Allergy Intolerance Observation"
            report_type="qweb-pdf"
            name="hc_allergy_intolerance.report_allergy_intolerance_observation"/>

</odoo>

```

**Comment by luigisison** [comment]
Issue: How to display `Reaction Notes`

![image](https://user-images.githubusercontent.com/8397319/29444978-a07aa620-8398-11e7-99c4-732fafb4e513.png)

**Comment by luigisison** [comment]
Issue: Change header

![image](https://user-images.githubusercontent.com/8397319/29445175-0976a380-839a-11e7-939d-d7d6f1024502.png)

**Comment by luigisison** [comment]
Issue: Make font size larger for `Event `and `Status`
Issue: define **Class** for `Event` as style=bold, color=blue, size=h2

![image](https://user-images.githubusercontent.com/8397319/29445215-46e0895c-839a-11e7-99ff-72d6e504e032.png)

**Comment by luigisison** [comment]
Code: `<tr style="font-size: 16px; font-weight: bold; color: #337ab7">`

![image](https://user-images.githubusercontent.com/8397319/29546144-596882b8-86a7-11e7-9c8f-07e6efa36d2e.png)
