### ISSUE TITLE
How to load child members

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#93]
In` hc_substance_models/hc_res_substance.p`y, define

```
class SubstanceCode(models.Model):
    _name = "hc.vs.substance.code"
    _description = "Substance Code"
    _inherit = ["hc.value.set.contains"]

 ....
    parent_child_ids = fields.Many2many(
        comodel_name="hc.vs.substance.code",
        relation="substance_code_parent_child_rel",
        column1="parent_id",
        column2="child_id",
        string="Parents",
        help="Parent substance code.")
    child_parent_ids = fields.Many2many(
        comodel_name="hc.vs.substance.code",
        relation="substance_code_child_parent_rel",
        column1="child_id",
        column2="parent_id",
        string="Children",
        help="Child substance code.")
```
File `hc.vs.substance.code.csv` loads `parent_child_ids`.

Question: How to load `child_parent_ids` afterwards?

**Comment by BipinRathod** [comment]
@api.onchange('code')
    def onchange_child(self):
        sub_code_obj = self.env['hc.vs.substance.code']
        for rec in self:
            rec.child_parent_ids = False
            if rec.code:
                child_ids = sub_code_obj.search([('parent_child_ids.code', '=', rec.code)])
                if child_ids:
                    rec.child_parent_ids = [(6,0,child_ids.ids)]

**Comment by luigisison** [comment]
Error: code **406464007** does not display its 3 children

**Comment by luigisison** [comment]
Calculate child count.
```

class SubstanceCode(models.Model):
    _name = "hc.vs.substance.code"
...
    child_count = fields.Integer(
        string="Count",
        help="Number of child members.")
```

**Comment by BipinRathod** [comment]
child_parent_ids = fields.Many2many(
        compute="_calc_child",
        comodel_name="hc.vs.substance.code",
        relation="substance_code_child_parent_rel",
        column1="child_id",
        column2="parent_id",
        string="Children",
        help="Child substance code.",
        store=True)
    child_count = fields.Integer(
        compute="_calc_child",
        string="Count",
        help="Number of child members.",
        store=True)

    @api.depends('code')
    def _calc_child(self):
        sub_code_obj = self.env['hc.vs.substance.code']
        for rec in self:
            rec.child_parent_ids = False
            rec.child_count = 0
            if rec.code:
                child_ids = sub_code_obj.search([('parent_child_ids.code', '=', rec.code)])
                if child_ids:
                    rec.child_count = int(len(child_ids))
                    rec.child_parent_ids = [(6,0,child_ids.ids)]
